<?php

namespace AppBundle\Repository;

/**
 * ClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClickRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get total clicks of Urls throughout the system
     *
     * @return int
     */
    public function countTotalClicks()
    {
        return $this->createQueryBuilder('t')
            ->select('COUNT(1)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
